[profile.default]
src = 'src'
out = 'out'
solc_version = '0.8.19'

[profile.ci.fuzz]
runs = 10_000


[rpc_endpoints]
manta = "https://pacific-rpc.manta.network/http"
mantatest = "https://pacific-rpc.sepolia-testnet.manta.network/http"

[etherscan]
manta = { key = "JHTUUN8MI" , chain = 169, url= "https://pacific-explorer.manta.network/api?"}
mantatest = { key = "JHTUUN8" , chain = 3441006, url = "https://pacific-explorer.sepolia-testnet.manta.network/api?"}

